# Generated by Django 4.1.1 on 2022-09-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ap_equip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=100)),
                ('count', models.IntegerField(blank=True)),
                ('cost', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coffe_sort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('count', models.IntegerField(blank=True)),
                ('cost', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='dop_ap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirop', models.CharField(max_length=100)),
                ('cost', models.FloatField(blank=True)),
                ('count', models.IntegerField(blank=True)),
            ],
        ),
    ]
